services:
  postfix:
    image: boky/postfix
    container_name: readkeeper_postfix
    ports:
      - "587:587"  # SMTP with STARTTLS
    environment:
      - ALLOWED_SENDER_DOMAINS=dev-mail.example.com
      - POSTFIX_myhostname=dev-mail.example.com
      - POSTFIX_mydomain=dev-mail.example.com
      - POSTFIX_debug_peer_level=2
      - RELAYHOST=
      - SMTP_SERVER=dev-mail.example.com
      - SMTP_PORT=587
      - SMTP_USERNAME=noreply
      - SMTP_PASSWORD=your_secure_password
      - SMTP_NETWORKS=0.0.0.0/0
      - POSTFIX_smtpd_sasl_type=dovecot
      - POSTFIX_smtpd_sasl_path=private/auth
      - POSTFIX_smtpd_sasl_auth_enable=yes
      - POSTFIX_smtpd_sasl_security_options=noanonymous
      - POSTFIX_smtpd_tls_auth_only=yes
    volumes:
      - ./docker/postfix/logs:/var/log
    restart: unless-stopped
    networks:
      - readkeeper_net

  # Add PostgreSQL database
  db:
    image: postgres:15-alpine
    container_name: readkeeper_postgres
    environment:
      - POSTGRES_USER=books
      - POSTGRES_PASSWORD=books
      - POSTGRES_DB=books
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - readkeeper_net

  # Add Redis for rate limiting
  redis:
    image: redis:alpine
    container_name: readkeeper_redis
    ports:
      - "6379:6379"
    networks:
      - readkeeper_net

  # Add MailHog for email testing
  mailhog:
    image: mailhog/mailhog
    container_name: readkeeper_mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1026:1025"  # SMTP server
    networks:
      - readkeeper_net

  app:
    build: .
    container_name: readkeeper_app
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://books:books@readkeeper_postgres:5432/books
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - readkeeper_net

networks:
  readkeeper_net:
    name: readkeeper_network

volumes:
  postgres_data: 